.DEFAULT_GOAL := all

.PHONY: convert_gui
.PHONY: convert_cli
.PHONY: deconvert

convert_gui:
	python3 setup_convert_gui_macos.py bdist_mac

convert_cli:
	python3 setup_convert_cli_macos.py build

deconvert:
	python3 setup_deconvert_macos.py build
