# encoding: utf8

# MIT License
#
# Copyright (c) 2017 R-Koubou
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#-------------------------------------------------------------
# File header/footer
#-------------------------------------------------------------

XML_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by XLS2ExpressionMap https://github.com/r-koubou/XLS2ExpressionMap -->
<InstrumentMap>
<string name="name" value="{name}" wide="true"/>"""

XML_FOOTER = """   <member name="controller">
      <int name="ownership" value="1"/>
   </member>
</InstrumentMap>
"""

#-------------------------------------------------------------
# Key switch
#-------------------------------------------------------------

KEY_SWITCH_HEADER = """
   <member name="slots">
      <int name="ownership" value="1"/>
      <list name="obj" type="obj">"""

KEY_SWITCH = """
         <obj class="PSoundSlot" ID="{uuid1}">
            <obj class="PSlotThruTrigger" name="remote" ID="{uuid2}">
               <int name="status" value="144"/>
               <int name="data1" value="-1"/>
            </obj>
            <obj class="PSlotMidiAction" name="action" ID="{uuid3}">
               <int name="version" value="600"/>
               <member name="noteChanger">
                  <int name="ownership" value="1"/>
                  <list name="obj" type="obj">
                     <obj class="PSlotNoteChanger" ID="{uuid4}">
                        <int name="channel" value="-1"/>
                        <float name="velocityFact" value="1"/>
                        <float name="lengthFact" value="1"/>
                        <int name="minVelocity" value="0"/>
                        <int name="maxVelocity" value="127"/>
                        <int name="transpose" value="0"/>
                        <int name="minPitch" value="0"/>
                        <int name="maxPitch" value="127"/>
                     </obj>
                  </list>
               </member>
{midimessage}
               <int name="channel" value="-1"/>
               <float name="velocityFact" value="1"/>
               <float name="lengthFact" value="1"/>
               <int name="minVelocity" value="0"/>
               <int name="maxVelocity" value="127"/>
               <int name="transpose" value="0"/>
               <int name="maxPitch" value="127"/>
               <int name="minPitch" value="0"/>
               <int name="key" value="0"/>
            </obj>
{articulations}
            <member name="name">
            <string name="s" value="{name}" wide="true"/>
            </member>
            <int name="color" value="{color}"/>
         </obj>"""

MIDI_MESSAGE_IN_KEYSWITCH_HEADER ="""               <member name="midiMessages">
                  <int name="ownership" value="1"/>
                  <list name="obj" type="obj">
"""

MIDI_MESSAGE_IN_KEYSWITCH_FOOTER ="""
                  </list>
               </member>"""


MIDI_MESSAGE_IN_KEYSWITCH = """                     <obj class="POutputEvent" ID="{uuid1}">
                        <int name="status" value="{midiMessage}"/>
                        <int name="data1" value="{data1}"/>
                        <int name="data2" value="{data2}"/>
                     </obj>
"""

EMPTY_MIDI_MESSAGE_IN_KEYSWITCH = """               <member name="midiMessages">
                  <int name="ownership" value="1"/>
               </member>"""


ARTICULATION_IN_SLOT_HEADER = """            <member name="sv">
               <int name="ownership" value="2"/>
               <list name="obj" type="obj">
"""

ARTICULATION_IN_SLOT = """                  <obj class="USlotVisuals" ID="{uuid1}">
                     <int name="displaytype" value="1"/>
                     <int name="articulationtype" value="1"/>
                     <int name="symbol" value="73"/>
                     <string name="text" value="{name}" wide="true"/>
                     <string name="description" value="{name}" wide="true"/>
                     <int name="group" value="{group}"/>
               </obj>"""

ARTICULATION_IN_SLOT_FOOTER = """
               </list>
            </member>"""

SLOTS_FOOTER = """
      </list>
   </member>
"""
#-------------------------------------------------------------
# Articulation
#-------------------------------------------------------------

ARTICULATION_HEADER = """
   <member name="slotvisuals">
      <int name="ownership" value="1"/>
      <list name="obj" type="obj">
"""

ARTICULATION = """         <obj class="USlotVisuals" ID="{uuid1}">
            <int name="displaytype" value="1"/>
            <int name="articulationtype" value="{type}"/>
            <int name="symbol" value="73"/>
            <string name="text" value="{name}" wide="true"/>
            <string name="description" value="{name}" wide="true"/>
            <int name="group" value="{group}"/>
         </obj>"""

ARTICULATION_FOOTER = """
      </list>
   </member>"""
