# encoding: utf8

#-------------------------------------------------------------
# File header/footer
#-------------------------------------------------------------

XML_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by XLS2ExpressionMap https://github.com/r-koubou/XLS2ExpressionMap -->
<InstrumentMap>
<string name="name" value="{name}" wide="true"/>"""

XML_FOOTER = """   <member name="controller">
      <int name="ownership" value="1"/>
   </member>
</InstrumentMap>
"""

#-------------------------------------------------------------
# Key switch
#-------------------------------------------------------------

KEY_SWITCH_HEADER = """
   <member name="slots">
      <int name="ownership" value="1"/>
      <list name="obj" type="obj">"""

KEY_SWITCH = """
         <obj class="PSoundSlot" ID="{uuid1}">
            <obj class="PSlotThruTrigger" name="remote" ID="{uuid2}">
               <int name="status" value="144"/>
               <int name="data1" value="-1"/>
            </obj>
            <obj class="PSlotMidiAction" name="action" ID="{uuid3}">
               <int name="version" value="600"/>
               <member name="noteChanger">
                  <int name="ownership" value="1"/>
                  <list name="obj" type="obj">
                     <obj class="PSlotNoteChanger" ID="{uuid4}">
                        <int name="channel" value="-1"/>
                        <float name="velocityFact" value="1"/>
                        <float name="lengthFact" value="1"/>
                        <int name="minVelocity" value="0"/>
                        <int name="maxVelocity" value="127"/>
                        <int name="transpose" value="0"/>
                        <int name="minPitch" value="0"/>
                        <int name="maxPitch" value="127"/>
                     </obj>
                  </list>
               </member>
{midimessage}
               <int name="channel" value="-1"/>
               <float name="velocityFact" value="1"/>
               <float name="lengthFact" value="1"/>
               <int name="minVelocity" value="0"/>
               <int name="maxVelocity" value="127"/>
               <int name="transpose" value="0"/>
               <int name="maxPitch" value="127"/>
               <int name="minPitch" value="0"/>
               <int name="key" value="0"/>
            </obj>
{articulations}
            <member name="name">
            <string name="s" value="{name}" wide="true"/>
            </member>
            <int name="color" value="{color}"/>
         </obj>"""

INT_TAG_IN_KEYSWITCH                = """               <int name="{name} value="{value}">\n"""
INT_MIDI_CC_NUM_TAG_IN_KEYSWITCH    = """               <int name="controller{ccNo}num" value="{ccNo}">\n"""
INT_MIDI_CC_VALUE_TAG_IN_KEYSWITCH  = """               <int name="controller{ccNo}value" value="{ccValue}">\n"""
INT_MIDI_PC_TAG_IN_KEYSWITCH        = """               <int name="program" value="{value}">\n"""

MIDI_MESSAGE_IN_KEYSWITCH_HEADER ="""               <member name="midiMessages">
                  <int name="ownership" value="1"/>
                  <list name="obj" type="obj">
"""

MIDI_MESSAGE_IN_KEYSWITCH_FOOTER ="""
                  </list>
               </member>"""


MIDI_MESSAGE_IN_KEYSWITCH = """                     <obj class="POutputEvent" ID="{uuid1}">
                        <int name="status" value="{midiMessage}"/>
                        <int name="data1" value="{data1}"/>
                        <int name="data2" value="{data2}"/>
                     </obj>
"""

EMPTY_MIDI_MESSAGE_IN_KEYSWITCH = """               <member name="midiMessages">
                  <int name="ownership" value="1"/>
               </member>"""


ARTICULATION_IN_SLOT_HEADER = """            <member name="sv">
               <int name="ownership" value="2"/>
               <list name="obj" type="obj">
"""

ARTICULATION_IN_SLOT = """                  <obj class="USlotVisuals" ID="{uuid1}">
                     <int name="displaytype" value="1"/>
                     <int name="articulationtype" value="1"/>
                     <int name="symbol" value="73"/>
                     <string name="text" value="{name}" wide="true"/>
                     <string name="description" value="{name}" wide="true"/>
                     <int name="group" value="{group}"/>
               </obj>"""

ARTICULATION_IN_SLOT_FOOTER = """
               </list>
            </member>"""

SLOTS_FOOTER = """
      </list>
   </member>
"""
#-------------------------------------------------------------
# Articulation
#-------------------------------------------------------------

ARTICULATION_HEADER = """
   <member name="slotvisuals">
      <int name="ownership" value="1"/>
      <list name="obj" type="obj">
"""

ARTICULATION = """         <obj class="USlotVisuals" ID="{uuid1}">
            <int name="displaytype" value="1"/>
            <int name="articulationtype" value="{type}"/>
            <int name="symbol" value="73"/>
            <string name="text" value="{name}" wide="true"/>
            <string name="description" value="{name}" wide="true"/>
            <int name="group" value="{group}"/>
         </obj>"""

ARTICULATION_FOOTER = """
      </list>
   </member>"""
